### ISSUE TITLE
Understanding the output. 

### ISSUE THREAD

**Issue by ghost** [sdzhao/dpm#1]
Hello ( : 

First of all, thank you four this work and the shared scripts.  I am trying to play a bit with your script but I can't fully understand the output, unfortunately. Take your example script for example. I have run this given line :
 
" fit.aic <- dpm(X1.t,X0.t,nlambda=10,tuning="aic") " [in your script called example.R ]

In the output, I have 10 differential networks estimated and I don't know which one is optimum. Could you help me? 

Thanks in advance, 

Emmanuel.

**Comment by sdzhao** [comment]
Hi Emmanuel, your fit.aic object is a list that contains an element named opt. This provides the index of the optimal estimated matrix.

So fit.aic$opt should tell you which of the differential networks is optimal given your tuning criterion.

Hope this helps!

**Comment by ghost** [comment]
By doing so, I get this : 

> fit.aic$opt
max   1  L1  sp   F  nc 
  1     10   3   4   5  10

Which one of the 10 differential networks is the best in this context? 

Thanks for your previous answer!

**Comment by sdzhao** [comment]
the "max" "1", "L1", etc. give you the index that is optimal for the different loss functions. so network 1 is best for when loss is measured using the max norm, network 10 is best using the 1-norm, 3 is best using the L1 norm, etc.

**Comment by ghost** [comment]
Ok, I clearly understand now. Thanks a lot again !!! 

Emmanuel
