### ISSUE TITLE
Data simlation 

### ISSUE THREAD

**Issue by Deramaka** [sdzhao/dpm#2]
Hello :) 

I am currently trying to reproduce some parts of your paper. I am especially quite interested in the part of the article 5·1. Settings (SIMULATIONS).  Could you give me more information about how you have done that part and in particular the beginning : 

_For each p, the support of (\sigma_x)^-1 was first generated according to a network with p(p − 1)/10
edges and a power-law degree distribution with an expected power parameter of 2, which should
mimic real-world networks. This still gives a relatively sparse network, since only 20% of all possible
edges are present, but the power-law structure creates hub nodes, which make certain rows and 
columns non-sparse._

Thanks in advance, 

Deramaka

**Comment by sdzhao** [comment]
I dug out my old code and here's the function that creates the precision matrix. Hope this helps!

library(igraph);
Omega1 <- function(p,perc.e=0.2,power=2,rdiv=4)
{
    g1 <- static.power.law.game(p,p*(p-1)/2*perc.e,
                                exponent.out=power);
    O1 <- get.adjacency(g1,sparse=FALSE);
    O1[O1==1] <- sample(c(-1,1),sum(O1==1),replace=TRUE)*
        runif(sum(O1==1),0.2,0.5);
    O1 <- apply(O1,1,function(r){ return(r/rdiv); });
    diag(O1) <- 1;
    O1 <- (O1+t(O1))/2;
    
    return(list(g1=g1,O1=O1,deg=degree(g1)));
}

**Comment by Deramaka** [comment]
Could it be possible that you meant _g1 <- static.power.law.game(p,**(p*(p-1)/2)*perc.e**,exponent.out=power);_
instead of what you have written ? 

Tanks for your previous answer! :)

**Comment by Deramaka** [comment]
You meant (p x (p-1)/2) x perc.e instead of p x (p-1)/2perc.e, right ? 

Thanks for your previous answer!

**Comment by sdzhao** [comment]
yes, you’re right. I’m not sure how that multiplication got deleted. sorry about that!

**Comment by Deramaka** [comment]
Ok, all right then.  Thanks a lot for helping! :)
